<!-- generated by gendocs from the command registry; do not edit by hand -->

# rmdir

Delete a database and everything in it

## Synopsis

```
cdb rmdir <path> [flags]
```

## Description

Delete a database and everything in it.

Destructive: asks for confirmation unless `--yes` is given.

## Arguments

Takes exactly 1 argument.

## Global flags

| Flag | Type | Default | Description |
|---|---|---|---|
| `--anonymous` | bool | `false` | connect without credentials, and do not ask for any |
| `--color` | string |  | colour: auto, always or never |
| `--format` | string |  | output format: table or json |
| `--json` | bool | `false` | print raw JSON instead of a table |
| `--pager` | string |  | pager command, or off |
| `--path` | string |  | starting virtual path |
| `--profile` | string |  | connection profile to use, overriding CDB_PROFILE and the default |
| `--replication-url` | string |  | address the server should use to reach itself for replication, overriding the profile and CDB_REPLICATION_URL |
| `--url` | string |  | server URL, overriding the profile and CDB_URL |
| `--verbose` | bool | `false` | include raw status codes and reasons in errors |
| `--yes` | bool | `false` | skip confirmation prompts |

## Examples

```
$ cdb rmdir /movies-copy --yes
Deleted database "movies-copy".
```

## See also

[`mkdir`](mkdir.md), [`rm`](rm.md)
