package main

import (
	"flag"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/sriannamalai/CDB.CLI/internal/command"
)

var update = flag.Bool("update", false, "rewrite the golden files from the current registry")

// committedDir is docs/reference, relative to this package.
const committedDir = "../../../docs/reference"

func TestPageGolden(t *testing.T) {
	c, ok := command.Default().Lookup("rmdir")
	if !ok {
		t.Fatal("rmdir is not registered")
	}
	checkGolden(t, "rmdir.md.golden", page(c))
}

func TestIndexGolden(t *testing.T) {
	checkGolden(t, "README.md.golden", index(command.Default()))
}

// TestCheckPassesOnCommittedTree is the test the CI step duplicates: it fails
// the moment a command's flags, summary or example change without the pages
// under docs/reference being regenerated.
func TestCheckPassesOnCommittedTree(t *testing.T) {
	diff, err := checkDir(committedDir, generate(command.Default()))
	if err != nil {
		t.Fatalf("checkDir: %v", err)
	}
	if diff != "" {
		t.Errorf("docs/reference is out of date; run \"go run ./internal/tools/gendocs\":\n%s", diff)
	}
}

func TestGenerateCoversEveryCommand(t *testing.T) {
	reg := command.Default()
	files := generate(reg)
	if _, ok := files[indexFile]; !ok {
		t.Errorf("generate did not produce %s", indexFile)
	}
	for _, c := range reg.All() {
		if _, ok := files[c.Name+".md"]; !ok {
			t.Errorf("generate did not produce a page for %q", c.Name)
		}
	}
	if want := len(reg.All()) + 1; len(files) != want {
		t.Errorf("generate produced %d files, want %d", len(files), want)
	}
}

// TestWriteThenCheckRoundTrips proves -check agrees with a fresh write, and
// that it reports the three ways a tree can drift.
func TestWriteThenCheckRoundTrips(t *testing.T) {
	dir := t.TempDir()
	files := generate(command.Default())
	if err := writeDir(dir, files); err != nil {
		t.Fatalf("writeDir: %v", err)
	}
	diff, err := checkDir(dir, files)
	if err != nil {
		t.Fatalf("checkDir: %v", err)
	}
	if diff != "" {
		t.Fatalf("checkDir on a freshly written tree = %q, want no difference", diff)
	}

	if err := os.WriteFile(filepath.Join(dir, "ls.md"), []byte("hand edited\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := os.Remove(filepath.Join(dir, "pwd.md")); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(dir, "stray.md"), []byte("stray\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	diff, err = checkDir(dir, files)
	if err != nil {
		t.Fatalf("checkDir: %v", err)
	}
	for _, want := range []string{"missing", "pwd.md", "out of date", "ls.md", "not generated by gendocs", "stray.md"} {
		if !strings.Contains(diff, want) {
			t.Errorf("checkDir report is missing %q:\n%s", want, diff)
		}
	}
}

func TestArgumentRule(t *testing.T) {
	cases := []struct {
		min, max int
		want     string
	}{
		{0, 0, "Takes no arguments."},
		{0, -1, "Takes any number of arguments."},
		{1, -1, "Takes at least 1 argument."},
		{2, 2, "Takes exactly 2 arguments."},
		{0, 1, "Takes at most 1 argument."},
		{1, 3, "Takes between 1 and 3 arguments."},
	}
	for _, tc := range cases {
		got := argumentRule(command.Command{MinArgs: tc.min, MaxArgs: tc.max})
		if got != tc.want {
			t.Errorf("argumentRule(min=%d max=%d) = %q, want %q", tc.min, tc.max, got, tc.want)
		}
	}
}

func TestSeeAlsoNamesAreRegistered(t *testing.T) {
	reg := command.Default()
	for name, related := range seeAlso {
		if _, ok := reg.Lookup(name); !ok {
			t.Errorf("seeAlso has an entry for %q, which is not a command", name)
		}
		for _, r := range related {
			if _, ok := reg.Lookup(r); !ok {
				t.Errorf("seeAlso[%q] names %q, which is not a command", name, r)
			}
		}
	}
}

func checkGolden(t *testing.T, name, got string) {
	t.Helper()
	path := filepath.Join("testdata", name)
	if *update {
		if err := os.MkdirAll("testdata", 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(path, []byte(got), 0o644); err != nil {
			t.Fatal(err)
		}
		return
	}
	want, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read golden: %v (run: go test ./internal/tools/gendocs -update)", err)
	}
	if got != string(want) {
		t.Errorf("generated page does not match %s:\n--- got ---\n%s\n--- want ---\n%s", path, got, want)
	}
}
