// Command gendocs writes the reference pages under docs/reference from the
// command registry, so that the documentation and the binary cannot disagree
// about a flag, an argument count or a summary.
package main

import (
	"fmt"
	"sort"
	"strings"

	"github.com/spf13/pflag"
	"github.com/sriannamalai/CDB.CLI/internal/cli"
	"github.com/sriannamalai/CDB.CLI/internal/command"
)

// header is the first line of every generated file. A reader who opens one of
// these pages to fix a typo needs to know where the text really comes from.
const header = "<!-- generated by gendocs from the command registry; do not edit by hand -->"

// indexFile is the name of the index page inside the output directory.
const indexFile = "README.md"

// seeAlso lists the commands worth reading next, per command. It is a static
// map rather than something derived, because "what should I read next" is an
// editorial judgement the registry does not hold.
var seeAlso = map[string][]string{
	"attach":       {"fetch", "cat", "rm"},
	"backup":       {"restore", "replicate"},
	"cat":          {"put", "edit", "ls"},
	"cd":           {"pwd", "ls"},
	"clear":        {"help"},
	"conflicts":    {"resolve", "cat"},
	"connect":      {"profiles", "session"},
	"cp":           {"replicate", "put"},
	"edit":         {"cat", "put"},
	"exit":         {"clear"},
	"fetch":        {"attach", "cat"},
	"find":         {"query", "ls"},
	"help":         {"history"},
	"history":      {"help"},
	"info":         {"ls", "session"},
	"ls":           {"cd", "info", "find"},
	"mkdir":        {"rmdir", "info"},
	"profiles":     {"connect", "session"},
	"put":          {"cat", "edit", "rm"},
	"pwd":          {"cd"},
	"query":        {"find", "ls"},
	"replicate":    {"replications", "cp", "backup"},
	"replications": {"replicate"},
	"resolve":      {"conflicts", "cat"},
	"restore":      {"backup", "mkdir"},
	"rm":           {"rmdir", "cat"},
	"rmdir":        {"mkdir", "rm"},
	"session":      {"connect", "profiles"},
}

// generate renders every page for a registry, keyed by file name. The map is
// the whole of the output directory: -check treats a file that is present on
// disk and absent here as stale.
func generate(reg *command.Registry) map[string]string {
	out := map[string]string{indexFile: index(reg)}
	for _, c := range reg.All() {
		out[c.Name+".md"] = page(c)
	}
	return out
}

// fileNames returns the generated file names in sorted order.
func fileNames(files map[string]string) []string {
	names := make([]string, 0, len(files))
	for n := range files {
		names = append(names, n)
	}
	sort.Strings(names)
	return names
}

// index renders the table of every command.
func index(reg *command.Registry) string {
	var b strings.Builder
	fmt.Fprintf(&b, "%s\n\n", header)
	b.WriteString("# cdb command reference\n\n")
	b.WriteString("One page per command, generated from the registry the binary itself runs on.\n")
	b.WriteString("For a task-shaped introduction read the [user guide](../UserGuide.md).\n\n")
	b.WriteString("A command marked **shell only** exists inside the interactive shell and has no\n")
	b.WriteString("`cdb <name>` form. A command marked **destructive** asks for confirmation\n")
	b.WriteString("before it acts, unless `--yes` is given.\n\n")
	b.WriteString("| Command | Aliases | Summary | Notes |\n")
	b.WriteString("|---|---|---|---|\n")
	for _, c := range reg.All() {
		fmt.Fprintf(&b, "| [`%s`](%s.md) | %s | %s | %s |\n",
			c.Name, c.Name, aliasList(c.Aliases), c.Summary, notes(c))
	}
	b.WriteString("\n## Global flags\n\n")
	b.WriteString("Every one-shot subcommand accepts these, before or after its own flags.\n")
	b.WriteString("Inside the shell only `--json`, `--yes`, `--verbose`, `--anonymous` and\n")
	b.WriteString("`--replication-url` are accepted on a line; the rest have shell equivalents\n")
	b.WriteString("(`connect`, `cd`) or are read from `config.toml` for the whole session.\n\n")
	b.WriteString(flagTable(globalFlags()))
	return b.String()
}

// page renders one command's reference page.
func page(c command.Command) string {
	var b strings.Builder
	fmt.Fprintf(&b, "%s\n\n", header)
	fmt.Fprintf(&b, "# %s\n\n", c.Name)
	fmt.Fprintf(&b, "%s\n\n", c.Summary)

	b.WriteString("## Synopsis\n\n```\n")
	fmt.Fprintf(&b, "%s\n", synopsis(c))
	b.WriteString("```\n\n")
	if len(c.Aliases) > 0 {
		fmt.Fprintf(&b, "Aliases: %s\n\n", aliasList(c.Aliases))
	}

	b.WriteString("## Description\n\n")
	fmt.Fprintf(&b, "%s.\n", strings.TrimSuffix(c.Summary, "."))
	if c.Details != "" {
		fmt.Fprintf(&b, "\n%s\n", strings.TrimRight(c.Details, "\n"))
	}
	if c.ShellOnly {
		b.WriteString("\nShell only: this command runs inside the interactive shell and has no\n`cdb " + c.Name + "` form.\n")
	}
	if c.Destructive {
		b.WriteString("\nDestructive: asks for confirmation unless `--yes` is given.\n")
	}
	b.WriteString("\n## Arguments\n\n")
	fmt.Fprintf(&b, "%s\n", argumentRule(c))

	if flags := commandFlags(c); len(flags) > 0 {
		b.WriteString("\n## Flags\n\n")
		b.WriteString(flagTable(flags))
	}
	b.WriteString("\n## Global flags\n\n")
	if c.ShellOnly {
		b.WriteString("Of these, only `--json`, `--yes`, `--verbose` and `--anonymous` may be typed\non a shell line; the rest belong to the one-shot front end.\n\n")
	}
	b.WriteString(flagTable(globalFlags()))

	if c.Example != "" {
		b.WriteString("\n## Examples\n\n```\n")
		fmt.Fprintf(&b, "%s\n", strings.TrimRight(c.Example, "\n"))
		b.WriteString("```\n")
	}
	if related := seeAlso[c.Name]; len(related) > 0 {
		b.WriteString("\n## See also\n\n")
		links := make([]string, 0, len(related))
		for _, n := range related {
			links = append(links, fmt.Sprintf("[`%s`](%s.md)", n, n))
		}
		fmt.Fprintf(&b, "%s\n", strings.Join(links, ", "))
	}
	return b.String()
}

// synopsis is the command line shape, with the shell prompt for a shell-only
// command and the binary name for everything else.
func synopsis(c command.Command) string {
	prefix := "cdb "
	if c.ShellOnly {
		prefix = ""
	}
	line := prefix + c.Name
	if c.Usage != "" {
		line += " " + c.Usage
	}
	return line + " [flags]"
}

// argumentRule states the argument count MinArgs and MaxArgs enforce.
func argumentRule(c command.Command) string {
	switch {
	case c.MaxArgs == 0 && c.MinArgs == 0:
		return "Takes no arguments."
	case c.MaxArgs < 0 && c.MinArgs == 0:
		return "Takes any number of arguments."
	case c.MaxArgs < 0:
		return fmt.Sprintf("Takes at least %s.", plural(c.MinArgs))
	case c.MinArgs == c.MaxArgs:
		return fmt.Sprintf("Takes exactly %s.", plural(c.MinArgs))
	case c.MinArgs == 0:
		return fmt.Sprintf("Takes at most %s.", plural(c.MaxArgs))
	default:
		return fmt.Sprintf("Takes between %d and %s.", c.MinArgs, plural(c.MaxArgs))
	}
}

func plural(n int) string {
	if n == 1 {
		return "1 argument"
	}
	return fmt.Sprintf("%d arguments", n)
}

// flagInfo is one row of a flag table.
type flagInfo struct {
	Name        string
	Type        string
	Default     string
	Description string
}

// commandFlags reads the flags a command declares for itself, without the
// shared ones every command inherits: those are documented once, as global
// flags, instead of on all twenty-eight pages.
func commandFlags(c command.Command) []flagInfo {
	fs := pflag.NewFlagSet(c.Name, pflag.ContinueOnError)
	if c.Flags != nil {
		c.Flags(fs)
	}
	return collect(fs)
}

// globalFlags reads the flags the cobra root declares for every subcommand.
func globalFlags() []flagInfo {
	fs := pflag.NewFlagSet("cdb", pflag.ContinueOnError)
	cli.GlobalFlags(fs)
	return collect(fs)
}

// collect turns a flag set into sorted rows. pflag's VisitAll walks a sorted
// flag set in lexical order, which is what makes the output stable.
func collect(fs *pflag.FlagSet) []flagInfo {
	var out []flagInfo
	fs.VisitAll(func(f *pflag.Flag) {
		out = append(out, flagInfo{
			Name:        f.Name,
			Type:        f.Value.Type(),
			Default:     f.DefValue,
			Description: f.Usage,
		})
	})
	sort.Slice(out, func(i, j int) bool { return out[i].Name < out[j].Name })
	return out
}

// flagTable renders flag rows as a Markdown table.
func flagTable(flags []flagInfo) string {
	var b strings.Builder
	b.WriteString("| Flag | Type | Default | Description |\n")
	b.WriteString("|---|---|---|---|\n")
	for _, f := range flags {
		fmt.Fprintf(&b, "| `--%s` | %s | %s | %s |\n", f.Name, f.Type, defaultCell(f.Default), f.Description)
	}
	return b.String()
}

// defaultCell renders a flag's zero value as an empty cell rather than as an
// empty pair of backticks.
func defaultCell(def string) string {
	if def == "" || def == "[]" {
		return ""
	}
	return "`" + def + "`"
}

// aliasList renders a command's aliases as inline code, or an empty cell.
func aliasList(aliases []string) string {
	if len(aliases) == 0 {
		return ""
	}
	out := make([]string, 0, len(aliases))
	for _, a := range aliases {
		out = append(out, "`"+a+"`")
	}
	return strings.Join(out, ", ")
}

// notes renders the index table's marker column.
func notes(c command.Command) string {
	var out []string
	if c.ShellOnly {
		out = append(out, "shell only")
	}
	if c.Destructive {
		out = append(out, "destructive")
	}
	return strings.Join(out, ", ")
}
