package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/sriannamalai/CDB.CLI/internal/command"
)

func main() {
	out := flag.String("out", filepath.Join("docs", "reference"), "directory to write the reference pages into")
	check := flag.Bool("check", false, "report, and exit non-zero, when the committed pages differ from what would be generated")
	flag.Parse()

	files := generate(command.Default())
	if *check {
		diff, err := checkDir(*out, files)
		if err != nil {
			fmt.Fprintln(os.Stderr, "gendocs:", err)
			os.Exit(1)
		}
		if diff != "" {
			fmt.Fprint(os.Stderr, diff)
			fmt.Fprintf(os.Stderr, "run \"go run ./internal/tools/gendocs\" and commit the result\n")
			os.Exit(1)
		}
		return
	}
	if err := writeDir(*out, files); err != nil {
		fmt.Fprintln(os.Stderr, "gendocs:", err)
		os.Exit(1)
	}
}

// writeDir writes every page, creating the directory when it is missing.
func writeDir(dir string, files map[string]string) error {
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}
	for _, name := range fileNames(files) {
		if err := os.WriteFile(filepath.Join(dir, name), []byte(files[name]), 0o644); err != nil {
			return err
		}
	}
	return nil
}

// checkDir compares the committed tree with what would be generated and
// returns a human-readable summary of the difference, or "" when they agree.
// It reports the three ways they can disagree separately, because the fix
// differs: a stale page is regenerated, an extra page is deleted by hand.
func checkDir(dir string, files map[string]string) (string, error) {
	var missing, stale []string
	for _, name := range fileNames(files) {
		got, err := os.ReadFile(filepath.Join(dir, name))
		switch {
		case os.IsNotExist(err):
			missing = append(missing, name)
			continue
		case err != nil:
			return "", err
		}
		if string(got) != files[name] {
			stale = append(stale, name)
		}
	}
	extra, err := extraFiles(dir, files)
	if err != nil {
		return "", err
	}
	var b strings.Builder
	report := func(label string, names []string) {
		if len(names) == 0 {
			return
		}
		fmt.Fprintf(&b, "%s (%d):\n", label, len(names))
		for _, n := range names {
			fmt.Fprintf(&b, "  %s\n", filepath.Join(dir, n))
		}
	}
	report("missing", missing)
	report("out of date", stale)
	report("not generated by gendocs", extra)
	return b.String(), nil
}

// extraFiles lists the Markdown files in dir that gendocs would not write.
func extraFiles(dir string, files map[string]string) ([]string, error) {
	entries, err := os.ReadDir(dir)
	if os.IsNotExist(err) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	var out []string
	for _, e := range entries {
		if e.IsDir() || filepath.Ext(e.Name()) != ".md" {
			continue
		}
		if _, ok := files[e.Name()]; !ok {
			out = append(out, e.Name())
		}
	}
	sort.Strings(out)
	return out, nil
}
